spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/paymentdb
      #uri:mongodb://admin:secret@mongodb:27017/paymentdb?authSource=admin
    #config:
    #import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: false   # ðŸ‘ˆ disables config server completely
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


